# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Classificator(object):
    def setupUi(self, Classificator):
        Classificator.setObjectName("Classificator")
        Classificator.resize(531, 364)
        Classificator.setMinimumSize(QtCore.QSize(531, 361))
        Classificator.setMaximumSize(QtCore.QSize(531, 364))
        self.centralwidget = QtWidgets.QWidget(Classificator)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(10, 310, 251, 31))
        self.lineName.setStyleSheet("QLineEdit {\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid black;\n"
"}")
        self.lineName.setText("")
        self.lineName.setObjectName("lineName")
        self.btnSaveTXT = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveTXT.setGeometry(QtCore.QRect(460, 310, 61, 31))
        self.btnSaveTXT.setStyleSheet("QPushButton {\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.btnSaveTXT.setObjectName("btnSaveTXT")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(400, 10, 121, 31))
        self.btnStart.setStyleSheet("QPushButton {\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.btnStart.setObjectName("btnStart")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.comboBox.setStyleSheet("\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(255, 255, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btnDownload = QtWidgets.QPushButton(self.centralwidget)
        self.btnDownload.setGeometry(QtCore.QRect(270, 10, 121, 31))
        self.btnDownload.setMouseTracking(False)
        self.btnDownload.setAutoFillBackground(False)
        self.btnDownload.setStyleSheet("QPushButton {\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.btnDownload.setCheckable(False)
        self.btnDownload.setObjectName("btnDownload")
        self.textWidget = QtWidgets.QListWidget(self.centralwidget)
        self.textWidget.setGeometry(QtCore.QRect(270, 50, 251, 251))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.textWidget.setFont(font)
        self.textWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.textWidget.setStyleSheet("border: 1px solid grey;\n"
"background-color: rgb(255, 255, 255);")
        self.textWidget.setObjectName("textWidget")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(10, 50, 251, 251))
        self.imageLabel.setAcceptDrops(False)
        self.imageLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid grey;")
        self.imageLabel.setText("")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.btnSaveCSV = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveCSV.setGeometry(QtCore.QRect(400, 310, 61, 31))
        self.btnSaveCSV.setStyleSheet("QPushButton {\n"
"    border: 1px solid grey;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid black;\n"
"    background-color: rgb(230, 230, 230);\n"
"}")
        self.btnSaveCSV.setObjectName("btnSaveCSV")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Classificator.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Classificator)
        self.statusBar.setStatusTip("")
        self.statusBar.setStyleSheet("")
        self.statusBar.setObjectName("statusBar")
        Classificator.setStatusBar(self.statusBar)

        self.retranslateUi(Classificator)
        QtCore.QMetaObject.connectSlotsByName(Classificator)

    def retranslateUi(self, Classificator):
        _translate = QtCore.QCoreApplication.translate
        Classificator.setWindowTitle(_translate("Classificator", "MainWindow"))
        self.lineName.setPlaceholderText(_translate("Classificator", "Введите имя пациента"))
        self.btnSaveTXT.setText(_translate("Classificator", ".txt"))
        self.btnStart.setText(_translate("Classificator", "Диагностировать"))
        self.comboBox.setItemText(0, _translate("Classificator", "Заболевания легких"))
        self.comboBox.setItemText(1, _translate("Classificator", "Заболевания кожи"))
        self.comboBox.setItemText(2, _translate("Classificator", "Заболевания крови"))
        self.btnDownload.setText(_translate("Classificator", "Загрузить снимок"))
        self.btnSaveCSV.setText(_translate("Classificator", ".csv"))
        self.label.setText(_translate("Classificator", "Сохранить отчет:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Classificator = QtWidgets.QMainWindow()
    ui = Ui_Classificator()
    ui.setupUi(Classificator)
    Classificator.show()
    sys.exit(app.exec_())
